# Generated by Django 3.0.7 on 2020-08-07 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='desc',
        ),
        migrations.AddField(
            model_name='articles',
            name='upload',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='время'),
            preserve_default=False,
        ),
    ]
