# Generated by Django 3.0.7 on 2020-08-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200808_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='desc',
            field=models.TextField(blank=True, verbose_name='текст'),
        ),
    ]
