# Generated by Django 3.0.7 on 2020-08-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_articles_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='desc',
            new_name='article',
        ),
        migrations.AddField(
            model_name='articles',
            name='short_desc',
            field=models.CharField(blank=True, max_length=256, verbose_name='краткое описание'),
        ),
    ]
